// Package voice is a local input method, independent from Assistant actions.
package voice

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net"
	"net/http"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

const MaxAudioBytes = 16000*2*120 + 44

type Config struct {
	Runtime, Model, Language string
	Threads                  int
	KeepLoaded               bool
}
type Service struct {
	mu       sync.Mutex
	cmd      *exec.Cmd
	done     chan struct{}
	endpoint string
	config   Config
	closed   bool
}
type Result struct {
	Text     string `json:"text"`
	Language string `json:"language"`
}

// ValidateWAV accepts only the bounded PCM input generated by the shared UI.
// Converting arbitrary audio formats or invoking ffmpeg is deliberately absent.
func ValidateWAV(audio []byte) error {
	if len(audio) < 46 || len(audio) > MaxAudioBytes || string(audio[:4]) != "RIFF" || string(audio[8:12]) != "WAVE" || string(audio[12:16]) != "fmt " || string(audio[36:40]) != "data" {
		return errors.New("voice requires a 16 kHz mono PCM WAV recording, at most two minutes")
	}
	if binary.LittleEndian.Uint32(audio[16:20]) != 16 || binary.LittleEndian.Uint16(audio[20:22]) != 1 || binary.LittleEndian.Uint16(audio[22:24]) != 1 || binary.LittleEndian.Uint32(audio[24:28]) != 16000 || binary.LittleEndian.Uint32(audio[28:32]) != 32000 || binary.LittleEndian.Uint16(audio[32:34]) != 2 || binary.LittleEndian.Uint16(audio[34:36]) != 16 || int(binary.LittleEndian.Uint32(audio[40:44])) != len(audio)-44 || int(binary.LittleEndian.Uint32(audio[4:8])) != len(audio)-8 || (len(audio)-44)%2 != 0 {
		return errors.New("invalid voice WAV layout")
	}
	return nil
}
func (s *Service) stopLocked(ctx context.Context) error {
	if s.cmd == nil {
		return nil
	}
	_ = s.cmd.Process.Kill()
	select {
	case <-s.done:
		s.cmd = nil
		s.endpoint = ""
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}
func (s *Service) Stop(ctx context.Context) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.closed = true
	return s.stopLocked(ctx)
}
func (s *Service) start(ctx context.Context, c Config) error {
	if s.cmd != nil {
		select {
		case <-s.done:
			s.cmd = nil
		default:
			if s.config == c {
				return nil
			}
			if err := s.stopLocked(ctx); err != nil {
				return err
			}
		}
	}
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return err
	}
	port := listener.Addr().(*net.TCPAddr).Port
	listener.Close()
	var token [24]byte
	if _, err := rand.Read(token[:]); err != nil {
		return err
	}
	prefix := "/" + hex.EncodeToString(token[:])
	cmd := exec.Command(c.Runtime, "-m", c.Model, "-t", strconv.Itoa(c.Threads), "-l", c.Language, "--host", "127.0.0.1", "--port", strconv.Itoa(port), "--request-path", prefix, "--public", filepath.Join(filepath.Dir(c.Runtime), "no-web-ui"), "-ng", "-mc", "0")
	cmd.Dir = filepath.Dir(c.Runtime)
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	if err := cmd.Start(); err != nil {
		return err
	}
	s.cmd = cmd
	s.done = make(chan struct{})
	done := s.done
	go func() { _ = cmd.Wait(); close(done) }()
	s.config = c
	s.endpoint = fmt.Sprintf("http://127.0.0.1:%d%s", port, prefix)
	ready, cancel := context.WithTimeout(ctx, 2*time.Minute)
	defer cancel()
	ticker := time.NewTicker(150 * time.Millisecond)
	defer ticker.Stop()
	for {
		select {
		case <-done:
			s.cmd = nil
			return errors.New("Whisper runtime exited before loading; verify runtime/model compatibility")
		case <-ready.Done():
			_ = cmd.Process.Kill()
			<-done
			s.cmd = nil
			return ready.Err()
		case <-ticker.C:
			conn, err := net.DialTimeout("tcp", fmt.Sprintf("127.0.0.1:%d", port), 100*time.Millisecond)
			if err == nil {
				conn.Close()
				return nil
			}
		}
	}
}
func (s *Service) Transcribe(ctx context.Context, c Config, audio []byte, vocabulary []string) (Result, error) {
	if err := ValidateWAV(audio); err != nil {
		return Result{}, err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return Result{}, errors.New("Voice service is stopped")
	}
	if err := ctx.Err(); err != nil {
		return Result{}, err
	}
	if err := s.start(ctx, c); err != nil {
		return Result{}, err
	}
	if !c.KeepLoaded {
		defer func() {
			stop, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			_ = s.stopLocked(stop)
		}()
	}
	var body bytes.Buffer
	form := multipart.NewWriter(&body)
	file, err := form.CreateFormFile("file", "recording.wav")
	if err != nil {
		return Result{}, err
	}
	if _, err := file.Write(audio); err != nil {
		return Result{}, err
	}
	if len(vocabulary) > 30 {
		vocabulary = vocabulary[:30]
	}
	prompt := strings.Join(vocabulary, ", ")
	if len(prompt) > 1000 {
		prompt = prompt[:1000]
	}
	for name, value := range map[string]string{"response_format": "json", "language": c.Language, "prompt": prompt, "temperature": "0.0", "carry_initial_prompt": "false"} {
		if err := form.WriteField(name, value); err != nil {
			return Result{}, err
		}
	}
	if err := form.Close(); err != nil {
		return Result{}, err
	}
	request, err := http.NewRequestWithContext(ctx, "POST", s.endpoint+"/inference", &body)
	if err != nil {
		return Result{}, err
	}
	request.Header.Set("Content-Type", form.FormDataContentType())
	client := http.Client{Timeout: 3 * time.Minute, CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse }}
	response, err := client.Do(request)
	if err != nil {
		return Result{}, err
	}
	defer response.Body.Close()
	raw, err := io.ReadAll(io.LimitReader(response.Body, 65537))
	if err != nil {
		return Result{}, err
	}
	if len(raw) > 65536 {
		return Result{}, errors.New("voice transcript exceeds limit")
	}
	if response.StatusCode != 200 {
		return Result{}, fmt.Errorf("Whisper transcription HTTP %d", response.StatusCode)
	}
	var result struct {
		Text          string `json:"text"`
		Language      string `json:"language"`
		Transcription []struct {
			Text string `json:"text"`
		} `json:"transcription"`
	}
	if err := json.Unmarshal(raw, &result); err != nil {
		return Result{}, err
	}
	if result.Text == "" {
		for _, segment := range result.Transcription {
			result.Text += segment.Text
		}
	}
	return Result{Text: strings.TrimSpace(result.Text), Language: result.Language}, nil
}
